#!/bin/bash

# Fusion specific items

alias fdp="cd ${WORKING}/fdp/fdp"
alias met="cd ${WORKING}/fdp/met"
alias ced="cd ${WORKING}/fdp/ced"
alias ctt="cd ${WORKING}/fdp/ctt"
alias aep="cd ${WORKING}/fdp/aep"
alias geo="cd ${WORKING}/fdp/geographic-information"
alias xcim="cd ${WORKING}/fdp/xcim"

