#!/bin/bash

#
# COPY things
#

alias copyInfo="cat ${HOME}/.reference/COPY_info"
alias vcopyInfo="vim ${HOME}/.reference/COPY_info"

alias copyStart="print_command /opt/RSM/COPY/tools/playlists/Start.sh"
alias copyStop="print_command /opt/RSM/COPY/tools/playlists/Start.sh"

