#!/bin/bash

set -e

source ${HOME}/.bashrc

function make_readable() {
  local PARENT_DIR CMD_PREFIX
  PARENT_DIR="."
  CMD_PREFIX=""

  while getopts ":sd:" opt; do
    case ${opt} in
      s)
        CMD_PREFIX="sudo ${CMD_PREFIX}"
        ;;
      d)
        PARENT_DIR="${OPTARG}"
        ;;
      \?)
        echo "Invalid option: -${OPTARG}" >&2
        return 1
        ;;
      :)
        echo "Option -${opt} requires an argument." >&2
        return 1
        ;;
    esac
  done
  
  shift $((OPTIND-1))
  if [ $# -eq 1 ]; then
    if [[ "${PARENT_DIR}" == "." ]]; then
      PARENT_DIR="$1"
    else
      echo "Unknown option(s): $*"
      return 2
    fi
  elif [ $# -gt 1 ]; then
    echo "Unknown option(s): $*"
    return 2
  fi

  # Make all directories +rx
  echo -en "\033[33m"
  echo -n "find ${PARENT_DIR} -type d -exec ${CMD_PREFIX}chmod a+rx {} "; echo '\;'
  echo -en "\033[0m"
  find ${PARENT_DIR} -type d -exec ${CMD_PREFIX}chmod a+rx {} \;

  # Make all files +r
  echo -en "\033[33m"
  echo -n "find ${PARENT_DIR} -type f -exec ${CMD_PREFIX}chmod a+r {} "; echo '\;'
  echo -en "\033[0m"
  find ${PARENT_DIR} -type f -exec ${CMD_PREFIX}chmod a+r {} \;
}

make_readable $*

